authman/*.lua usr/share/tarantool/authman/
authman/oauth/*.lua usr/share/tarantool/authman/oauth/
authman/utils/*.lua usr/share/tarantool/authman/utils/
authman/model/*.lua usr/share/tarantool/authman/model/
authman/model/oauth/*.lua usr/share/tarantool/authman/model/oauth/
authman/model/oauth/consumer/*.lua usr/share/tarantool/authman/model/oauth/consumer/
authman/migrations/*.lua usr/share/tarantool/authman/migrations/

